image: Visual Studio 2017

environment:
  nodejs_version: "12"

platform:
  - x64

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) x64
  - node --version
  - yarn install

before_build:
  - set NODE_ENV=production

build_script:
  - yarn lint
  - yarn bundle
  - yarn test
  - yarn package:publish

test: off